### ISSUE TITLE
Not enough components of "forces" on the /xServTopic topic

### ISSUE THREAD

**Issue by zesk1999** [mcsix/xela_server_ros#2] opened 2024-07-08 06:37 UTC
Curved Uskin tactile sensors attached to Allegro hand:
There is an element of the ROS node named "forces" where values change according to the force applied. However, there are only 10 x, y, and z components per sensor, even though there should be 30 (30 taxels per sensor). I am attaching messages from the topic /xServTopic  without forces applied. 
[Forces.docx](https://github.com/user-attachments/files/16123617/Forces.docx)

**Comment by mcsix** [comment] 2024-07-08 08:30
Could you send us the `Server` software version, the `xServ.ini` file, and the `XR21AFTC.xela` file (or if you use .xcal or .xdef, those as well) that you use? This could help us replicate the issue and find a possible cause.
Thank you

**Comment by mcsix** [comment] 2024-07-08 08:44
We have received the WeTransfer files as well; thank you. Yet from those, it looks like the ROS node has taken other information in for the force measurement. It has been reading `ups` values as force, which would explain why it only exists in the 10-taxel range. As such, have you changed the node's source at any point?
On line 465 of the `scripts/xela_service`, you can see the following:
```python
force_vals = msg_obj.get("calibrated", None)
    If force_vals is None:
        force_vals = []
    for i in range(0, len(force_vals), 3):
        forces.append(Forces())
        forces[-1].x, forces[-1].y, forces[-1].z = force_vals[i:i + 3]
    sensor.forces = forces
```
This allocation also ensures that no other value shall be used for calibrated forces, only if marked as `calibrated`, which `ups` is not.
The `ups` stands for updates per second, and with event-driven microcontrollers, they are usually low until the values change, in which case they start broadcasting more often.

If you have modified the code, please show me so I can help fix it. If not, I would need to figure out why I have been unable to reproduce this issue since it was first mentioned in a direct email.

**Comment by zesk1999** [comment] 2024-07-08 10:03
I cannot attach files with extension .xela and .ini here, but I sent you via mail. However, I did use "ups" values since the "calibrated" values did not give any output. I assume this was an issue.
Thank you.

**Comment by mcsix** [comment] 2024-07-08 10:13
Thank you.

Yes, that is the issue then. 
We will do some more testing for the force calibration for the curved fingertip and let you know once it can be downloaded from our support website.

I will now close the issue.

**Closed as completed by mcsix** 2024-07-08 10:13 UTC
